const en = {
  title: 'Identity console', intro: 'Accounts, applications and access configuration.', checking: 'Checking your session…', login: 'Sign in / register',
  disabled: 'The console is not initialized or its login client is unavailable. Ask the deployment operator to check AUTH_CONSOLE_ENABLED and the registered callback.',
  noAdmin: 'Manage your own spaces and account security here. Platform administration is available only to deployment-authorized administrators.',
  account: 'Your account', userId: 'User ID', signOut: 'Sign out', allOut: 'Sign out everywhere', signedOut: 'Signed out. Automatic restoration is paused until you sign in again.',
  unconfirmed: 'Local session cleared. Server revocation could not be confirmed; other sessions may still be active.',
  applications: 'Applications', users: 'Users', audit: 'Security audit', reload: 'Reload', next: 'Next page', first: 'First page', empty: 'No records.',
  name: 'Name', status: 'Status', version: 'Version', edit: 'Open', create: 'Create', save: 'Save changes', back: 'Back to applications', newApp: 'New application',
  permissions: 'Application action catalog', fixed: 'Fixed actions only. An empty selection grants no business actions; platform access never grants space membership.',
  clients: 'Login clients', services: 'Backend services', newClient: 'New login client', clientId: 'Client ID', type: 'Client type', scopes: 'Scopes', callbacks: 'Exact callbacks, one per line',
  clientWarning: 'Saving any client change revokes its existing grants. HTTPS is required, except loopback HTTP. Native custom schemes must use reverse-domain names.',
  newService: 'New backend service', rotate: 'Rotate secret', disable: 'Disable', enable: 'Restore', credential: 'Active credential ID',
  once: 'Save this secret securely now. It is shown only in this response and cannot be retrieved later.', show: 'Show secret', dismiss: 'Dismiss and clear',
  secret: 'Service secret', identity: 'Service client ID', serviceWarning: 'Rotation or disable immediately invalidates old secrets and service tokens. Never put a service secret in frontend code.',
  email: 'Verified email', details: 'Details', event: 'Event', outcome: 'Outcome', time: 'Time', actor: 'Actor', request: 'Request ID',
  confirm: 'Confirm change', cancel: 'Cancel', confirmWarning: 'This changes live access. Disabling a user, application or client revokes its sessions; restoring does not revive old tokens. Disabling your own account or console may sign you out.',
  success: 'Change saved.', uncertain: 'The outcome may be unknown. Read current state before another change; do not blindly repeat a create or rotation.',
  failed: 'Request failed. No automatic retry was made.', retryLogin: 'Sign in again', access: 'Deployment-managed access',
  errors: {
    VERSION_CONFLICT: 'Configuration changed elsewhere. Reload and review before saving again.', PLATFORM_ADMIN_REQUIRED: 'This account is not on the deployment administrator whitelist.',
    UNAUTHENTICATED: 'Your session is no longer valid. Sign in again.', LOGIN_REQUIRED: 'Please sign in.', INVALID_REQUEST: 'Check the input fields and callback list.',
    ALREADY_EXISTS: 'This client ID is already registered.', SERVICE_NOT_ACTIVE: 'The service or its application is unavailable.', APPLICATION_DISABLED: 'The application is disabled.',
    AUTH_UNAVAILABLE: 'Auth is temporarily unavailable.', NETWORK_ERROR: 'The request did not complete reliably.', INVALID_CONFIGURATION: 'Console configuration does not match this Auth origin.',
    STORAGE_UNAVAILABLE: 'Browser session storage is required for the login handoff.', NOT_FOUND: 'The record no longer exists.',
  } as Record<string, string>,
}
export const consoleCopy = { en, 'zh-CN': {
  title: '身份管理控制台', intro: '管理账号、应用与访问配置。', checking: '正在检查登录状态…', login: '登录 / 注册',
  disabled: '控制台尚未初始化，或其登录客户端不可用。请部署方检查 AUTH_CONSOLE_ENABLED 与登记的回调地址。',
  noAdmin: '你可以管理自己的空间和账号安全。平台管理仅向部署方指定的管理员开放。',
  account: '我的账号', userId: '用户 ID', signOut: '退出当前登录', allOut: '全部退出', signedOut: '已退出。再次主动登录前，不会自动恢复。',
  unconfirmed: '本地登录已清除，但未能确认服务端撤销，其他会话可能仍有效。',
  applications: '应用', users: '用户', audit: '安全审计', reload: '重新读取', next: '下一页', first: '第一页', empty: '暂无记录。',
  name: '名称', status: '状态', version: '版本', edit: '打开', create: '创建', save: '保存修改', back: '返回应用列表', newApp: '创建应用',
  permissions: '应用动作目录', fixed: '仅可选择固定动作。留空不授予业务动作；平台身份不等于空间成员身份。',
  clients: '登录客户端', services: '后端服务', newClient: '创建登录客户端', clientId: '客户端 ID', type: '客户端类型', scopes: 'Scope', callbacks: '精确回调地址，每行一个',
  clientWarning: '保存任何客户端修改都会撤销其已有授权。仅 loopback 允许 HTTP；原生自定义 scheme 须采用反向域名。',
  newService: '创建后端服务', rotate: '轮换 Secret', disable: '停用', enable: '恢复', credential: '有效凭据 ID',
  once: '请立即将 Secret 保存到安全位置。仅本次响应显示，关闭后无法再次查询。', show: '显示 Secret', dismiss: '关闭并清除',
  secret: '服务 Secret', identity: '服务客户端 ID', serviceWarning: '轮换或停用立即使旧 Secret 和服务 Token 失效。不能将服务 Secret 放入前端代码。',
  email: '已验证邮箱', details: '详情', event: '事件', outcome: '结果', time: '时间', actor: '操作者', request: '请求 ID',
  confirm: '确认变更', cancel: '取消', confirmWarning: '此操作会改变实际访问权限。停用用户、应用或客户端会撤销相应会话，恢复不会复活旧 Token。停用自己的账号或控制台可能导致当前登录失效。',
  success: '变更已保存。', uncertain: '操作结果可能尚不确定。请先重新读取状态，不能盲目重复创建或轮换。',
  failed: '请求失败，未自动重试。', retryLogin: '重新登录', access: '部署侧管理权限',
  errors: {
    VERSION_CONFLICT: '配置已被其他操作修改，请重新读取并核对后再保存。', PLATFORM_ADMIN_REQUIRED: '当前账号不在部署管理员白名单中。',
    UNAUTHENTICATED: '登录已失效，请重新登录。', LOGIN_REQUIRED: '请先登录。', INVALID_REQUEST: '请检查输入字段和回调地址。',
    ALREADY_EXISTS: '客户端 ID 已被登记。', SERVICE_NOT_ACTIVE: '服务或所属应用不可用。', APPLICATION_DISABLED: '应用已停用。',
    AUTH_UNAVAILABLE: 'Auth 暂时不可用。', NETWORK_ERROR: '未能可靠完成请求。', INVALID_CONFIGURATION: '控制台配置与当前 Auth 来源不匹配。',
    STORAGE_UNAVAILABLE: '登录交接需要浏览器 sessionStorage。', NOT_FOUND: '记录不存在。',
  } as Record<string, string>,
} }
