export const copy = {
  'zh-CN': {
    brandStatement: '一个账号，\n更多可能。', brandCaption: 'molis AI 一站式账号',
    loginMethods: '登录方式', accountLogin: '账号登录', notAvailable: '未开放',
    returnToApplication: '登录完成后将返回发起登录的应用。',
    eyebrow: 'molis AI', headline: '一站式账号', intro: '一个账号，开启更多可能。',
    login: '登录', register: '创建账号', reset: '找回密码', verify: '确认你的邮箱', complete: '确认登录账号',
    confirmAccountNotice: '请确认这是你要使用的账号；若不是，请取消。',
    confirmAccount: '确认账号并继续', cancelAccount: '不是我的账号，取消', accountId: '账号 ID',
    providerTitle: '确认登录方式', providerNotice: '继续前往所选账号的官方登录页面。你的 Google 或 Apple 密码不会交给 Auth。',
    google: '使用 Google 继续', apple: '使用 Apple 继续', otherMethod: '改用其他登录方式', orContinue: '或使用以下方式',
    description: '很高兴，再见到你。', registerDescription: '使用邮箱和密码创建账号。', resetDescription: '验证邮箱后设置新密码，所有旧登录将失效。',
    loginIdentifier: '账号或邮箱', email: '邮箱', password: '密码', newPassword: '新密码', name: '显示名称', remember: '记住邮箱', forgot: '忘记密码？',
    submit: '登录并继续', send: '发送验证邮件', sent: '验证邮件已排队。请打开邮件并点击确认，再回到此页面完成操作。',
    finishRegister: '创建账号', finishReset: '已确认邮箱，重置密码', confirm: '确认邮箱', confirmed: '邮箱已确认。请回到发起注册或找回密码的页面继续。',
    verifyDescription: '仅确认邮箱，不会自动创建账号、登录或修改密码。', passwordHint: '8–128 个字符',
    noTransaction: '当前页面没有有效的登录请求，请', signInAgain: '重新登录', checking: '正在检查登录请求…',
    restart: '重新开始登录', resetDone: '密码已重置，旧登录已失效。请使用新密码重新登录。', restartHint: '此操作无法安全重试，请重新开始登录。',
    invalidLink: '此链接无效或已失效，请从原应用重新发起。', request: '请求编号', mailUnavailable: '当前环境未启用邮件账号流程。',
    errors: {
      CONSOLE_NOT_ENABLED: '当前环境未启用 Auth 管理台，请联系管理员。',
      PASSWORD_MISMATCH: '两次输入的密码不一致。', EMAIL_FLOW_UNAVAILABLE: '邮件验证与找回密码暂不可用。',
      INVALID_CREDENTIALS: '账号或密码不正确，或该账号当前无法登录。', INVALID_PASSWORD: '密码需为 8–128 个字符。', PASSWORD_BLOCKED: '这个密码过于常见，请换一个不常见的长密码。',
      INVALID_TRANSACTION: '登录请求或邮箱证明无效，请检查是否已确认邮件；必要时重新开始。', INVALID_REQUEST: '请检查输入内容。',
      ACCOUNT_NOT_AVAILABLE: '该邮箱不能用于新建账号，请使用已有登录方式。', RESET_NOT_AVAILABLE: '无法重置此账号的本地密码，请使用原登录方式。',
      RATE_LIMITED: '操作过于频繁，请稍后再试。', AUTH_UNAVAILABLE: '认证服务暂时不可用，请稍后重新开始。',
      NETWORK_ERROR: '未能确认操作结果。为避免重复提交，请重新开始登录。', INVALID_RESPONSE: '无法验证服务响应，已停止跳转。',
      ORIGIN_NOT_ALLOWED: '此页面不属于当前应用的授权来源。', AUTH_ORIGIN_REQUIRED: '请在 Auth 页面完成此操作。',
      AUTH_INTERNAL_ERROR: '暂时无法完成操作，请重新开始。',
      PROVIDER_CANCELLED: '你已取消第三方登录，可以重新开始或选择其他登录方式。', PROVIDER_INTERRUPTED: '上次第三方登录未完成，请重新开始。',
      PROVIDER_NOT_ENABLED: '当前环境未启用这个登录方式，请选择其他方式。', PROVIDER_TRANSACTION_INVALID: '第三方登录请求已失效或不属于当前浏览器，请重新开始。',
      PROVIDER_UNAVAILABLE: '第三方登录服务暂时不可用，请稍后重新开始。', PROVIDER_CONFIGURATION_ERROR: '登录方式配置暂不可用，请联系管理员。',
      PROVIDER_AUTHORIZATION_FAILED: '第三方授权未完成，请重新开始。', PROVIDER_CODE_REJECTED: '本次授权已失效，请重新开始。',
      PROVIDER_RESPONSE_INVALID: '无法验证第三方响应，已停止登录。', PROVIDER_IDENTITY_INVALID: '无法验证第三方身份，已停止登录。',
      PROVIDER_TOO_MANY_PENDING: '未完成的登录过多，请完成或取消其他登录，或等待五分钟后重试。',
      ACCOUNT_LINK_REQUIRED: '该邮箱已有账号，需要验证已有登录方式后关联。此关联流程尚未开放，请先使用原登录方式。',
      MAILBOX_VERIFICATION_REQUIRED: '还需要验证邮箱所有权。此补充验证流程尚未开放，请先使用其他可用方式。',
      STORAGE_UNAVAILABLE: '浏览器无法保存本次跳转的短期信息，已停止操作。请允许此站点使用会话存储后重试。',
      LOGIN_CONFIRMATION_REQUIRED: '请先确认要登录的账号。', LOGIN_CANCELLED: '本次登录已取消，原有登录不会因此退出。',
      CONFIRMATION_TOO_MANY_PENDING: '待确认的登录过多，请先完成其他登录，或等待十分钟后重试。',
    } as Record<string, string>,
  },
  en: {
    brandStatement: 'One account.\nMore possibilities.', brandCaption: 'Your molis AI account',
    loginMethods: 'Sign-in methods', accountLogin: 'Account', notAvailable: 'Unavailable',
    returnToApplication: 'After signing in, you will return to the application that requested it.',
    eyebrow: 'molis AI', headline: 'One account.\nMore possibilities.', intro: 'Your molis AI experience starts here.',
    login: 'Sign in', register: 'Create account', reset: 'Reset password', verify: 'Confirm your email', complete: 'Confirm your account',
    confirmAccountNotice: 'Check that this is the account you intend to use; otherwise cancel.',
    confirmAccount: 'Confirm account and continue', cancelAccount: 'Not my account — cancel', accountId: 'Account ID',
    providerTitle: 'Confirm sign-in method', providerNotice: 'Continue to your provider’s official page. Your Google or Apple password is never sent to Auth.',
    google: 'Continue with Google', apple: 'Continue with Apple', otherMethod: 'Use another sign-in method', orContinue: 'Or continue with',
    description: 'Welcome back. Pick up where you left off.', registerDescription: 'Create an account with your email and password.', resetDescription: 'Verify your email to set a new password. All previous sessions will end.',
    loginIdentifier: 'Account or email', email: 'Email', password: 'Password', newPassword: 'New password', name: 'Display name', remember: 'Remember email', forgot: 'Forgot password?',
    submit: 'Sign in and continue', send: 'Send verification email', sent: 'Your email is queued. Open it and confirm, then return here to finish.',
    finishRegister: 'Create account', finishReset: 'Email confirmed — reset password', confirm: 'Confirm email', confirmed: 'Email confirmed. Return to the page where you started registration or password reset.',
    verifyDescription: 'This only confirms your email. It will not create an account, sign you in, or change a password.', passwordHint: '8–128 characters',
    noTransaction: 'This page has no valid sign-in request. Please ', signInAgain: 'sign in again', checking: 'Checking your sign-in request…',
    restart: 'Start sign-in again', resetDone: 'Password reset. Previous sessions have ended. Sign in with your new password.', restartHint: 'This operation cannot be retried safely. Start sign-in again.',
    invalidLink: 'This link is invalid or expired. Start again from your app.', request: 'Request ID', mailUnavailable: 'Email account flows are not enabled in this environment.',
    errors: {
      CONSOLE_NOT_ENABLED: 'The Auth console is not enabled in this environment. Contact your administrator.',
      PASSWORD_MISMATCH: 'The passwords do not match.', EMAIL_FLOW_UNAVAILABLE: 'Email verification and password recovery are unavailable.',
      INVALID_CREDENTIALS: 'The email or password is incorrect, or this account cannot sign in.', INVALID_PASSWORD: 'Use a password of 8–128 characters.', PASSWORD_BLOCKED: 'This password is too common. Choose a less predictable long password.',
      INVALID_TRANSACTION: 'The sign-in request or email proof is invalid. Confirm the email, or start again.', INVALID_REQUEST: 'Please check your input.',
      ACCOUNT_NOT_AVAILABLE: 'An account cannot be created with this email. Use your existing sign-in method.', RESET_NOT_AVAILABLE: 'This account’s local password cannot be reset. Use your original sign-in method.',
      RATE_LIMITED: 'Too many requests. Please wait before trying again.', AUTH_UNAVAILABLE: 'Authentication is temporarily unavailable. Please start again later.',
      NETWORK_ERROR: 'The result could not be confirmed. Start sign-in again to avoid duplicate submissions.', INVALID_RESPONSE: 'The service response could not be verified. Navigation stopped.',
      ORIGIN_NOT_ALLOWED: 'This page is not an authorized origin for the app.', AUTH_ORIGIN_REQUIRED: 'Complete this step on the Auth page.',
      AUTH_INTERNAL_ERROR: 'The operation could not be completed. Please start again.',
      PROVIDER_CANCELLED: 'Provider sign-in was cancelled. Start again or choose another method.', PROVIDER_INTERRUPTED: 'The previous provider sign-in did not finish. Please start again.',
      PROVIDER_NOT_ENABLED: 'This sign-in method is not enabled. Choose another method.', PROVIDER_TRANSACTION_INVALID: 'This provider request has expired or belongs to another browser. Start again.',
      PROVIDER_UNAVAILABLE: 'The provider is temporarily unavailable. Please start again later.', PROVIDER_CONFIGURATION_ERROR: 'This sign-in method is unavailable due to configuration. Contact an administrator.',
      PROVIDER_AUTHORIZATION_FAILED: 'Provider authorization did not complete. Start again.', PROVIDER_CODE_REJECTED: 'This authorization is no longer valid. Start again.',
      PROVIDER_RESPONSE_INVALID: 'The provider response could not be verified. Sign-in stopped.', PROVIDER_IDENTITY_INVALID: 'The provider identity could not be verified. Sign-in stopped.',
      PROVIDER_TOO_MANY_PENDING: 'Too many pending sign-ins. Finish or cancel another attempt, or wait five minutes.',
      ACCOUNT_LINK_REQUIRED: 'An account already uses this email and needs verification before linking. Linking is not available yet; use the existing sign-in method.',
      MAILBOX_VERIFICATION_REQUIRED: 'Mailbox ownership needs additional verification. That flow is not available yet; use another available method.',
      STORAGE_UNAVAILABLE: 'The browser cannot retain short-lived navigation information. Allow session storage for this site, then try again.',
      LOGIN_CONFIRMATION_REQUIRED: 'Confirm the account before continuing.', LOGIN_CANCELLED: 'This sign-in was cancelled. Your existing sign-in was not logged out.',
      CONFIRMATION_TOO_MANY_PENDING: 'Too many pending confirmations. Finish another sign-in, or wait ten minutes.',
    } as Record<string, string>,
  },
}
